In [1]:
from tensorflow import keras

In [2]:
from src.models import Sequential
from src.layers import *
from src.activation_functions import *
from src.loss_functions import *

In [3]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, RocCurveDisplay, roc_curve
from sklearn.metrics import roc_auc_score, f1_score, balanced_accuracy_score
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from sklearn import preprocessing

In [11]:
lin1 = Linear(n_inputs=1, n_outputs=3)
lin1.weights = np.asarray([0.1, -0.1, 0.3])

In [12]:
out1 = Linear(n_inputs=3, n_outputs=1)
out1.weights = np.asarray([[0.7], [0.9], [-0.4]])

In [13]:
model = Sequential(epochs=1, learning_rate=0.01, loss_function=MeanAbsoluteError())

In [14]:
model.add(lin1)
model.add(out1)

In [38]:
x = np.asarray([0.5])
x @ lin1.weights

In [15]:
model.train(x, np.asarray([[0.1]]))

[0.5]
[[-0.34000001]]
[[-0.238      -0.306       0.13600001]]
Epoch: 0, Loss: 0.16030251625306044


In [16]:
for l in model.layers:
    print(l.weights)

[[ 0.10119 -0.09847  0.29932]]
[[ 0.70017]
 [ 0.89983]
 [-0.39949]]


In [17]:
loss = 2 * 1 * (out1_out - 0.1)
loss

NameError: name 'out1_out' is not defined

In [ ]:
out1.backward(loss, 0.01)

In [ ]:
out1.weights

In [ ]:
out1.bias

In [ ]:
input_error = loss @ out1.weights.T
input_error

In [ ]:
out1.weights