In [1]:
from src.models import Sequential
from src.layers import *
from src.activation_functions import *
from src.loss_functions import *

In [2]:
soft = Softmax()
cross = CrossEntropy()

In [3]:
v = np.array([-1.0, -1.0, 1.0]) # unscaled logits
t = np.array([0.0,1.0,0.0])     # target probability distribution

In [4]:
soft_out = soft.forward(v)
soft_out

array([0.10650698, 0.10650698, 0.78698604])

In [5]:
cross.forward(soft_out, t)

2.2395447662218846

In [6]:
cross_back = cross.backward()
cross_back

array([-0.       , -9.3890561, -0.       ])

In [7]:
soft_back = soft.backward(cross_back)
soft_back

array([[ 0.09516324, -0.01134374, -0.08381951],
       [-0.01134374,  0.09516324, -0.08381951],
       [-0.08381951, -0.08381951,  0.16763901]])

In [8]:
cross_back @ soft_back

array([ 0.10650698, -0.89349302,  0.78698604])